<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\PadelCourtManagement.Application\PadelCourtManagement.Application.csproj" />
    <ProjectReference Include="..\PadelCourtManagement.Infrastructure\PadelCourtManagement.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1e10f078-e8ba-4545-99b5-3838ff7f5e90</UserSecretsId>
  </PropertyGroup>

</Project>
